version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    security: true

  # - package-ecosystem: "npm"
  #   directory: "/"
  #   schedule:
  #     interval: "daily" # weekly
  #   open-pull-requests-limit: 1
  #   target-branch: "master"
  #   package-regex: "^(packages/|/)?"
  #   security: true
