enableGlobalCache: true

logFilters:
  - code: YN0002
    level: discard

nmMode: hardlinks-local

nodeLinker: node-modules

plugins:
  spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.6.3.cjs
