name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout branch
      uses: actions/checkout@v3

    - name: Determine Node.js version from .nvmrc
      id: node_version
      run: echo "node_version=$(cat .nvmrc) >> $GITHUB_OUTPUT"

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.node_version.outputs.node_version }}

    - name: Install dependencies
      run: |
        yarn --immutable

    - name: Build
      run:
        yarn workspaces foreach run build
