name: Deploy Web Client

on:
  push:
    branches: [ "master" ]

env:
  PROJECT_ID: ${{ secrets.GCP_WEB_PROJECT_ID }}
  SERVICE: ${{ secrets.GCP_WEB_PROJECT_ID }}
  REGION: ${{ secrets.GCP_WEB_PROJECT_REGION }}

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_WEB_CRED }}'

      - name: Deploy
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./packages/live-code-platform-web-client

      - name: URL
        run: echo ${{ steps.deploy.outputs.url }}
